### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by exactmaterial** [ajmeese7/spambot#2]
Nvm found the issue, i'll post an update soon - 04.03

```
node bot.js
/mypath_censored/bot.js:8
client.on("message", async message => {
                     ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
```

Base system : Debian GNU/Linux 9 (stretch) 64-bit
4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
Node js version : v6.14.1
Npm version : v3.10.10

It's not a dependency issue : 

"npm install 
npm WARN spambot@1.0.0 No repository field.
"
Installed: 
- bufferutil@^3.0.3
- discord.js@11.3.2 
- erlpack@discordapp/erlpack
- libsodium-wrappers@^0.7.3
- node-opus@^0.2.7
- opusscript@^0.0.6
- sodium@^2.0.3
- uws@^9.14.0

Can you tell me which version of node.js supported? Whats your setup?
Thanks

**Comment by ajmeese7** [comment]
Any updates on your problem? When I get home I can check which version I was running and let you know

**Comment by ajmeese7** [comment]
I just tried running it with Node 8.11.1 and it worked fine from the node command prompt, Manjaro terminal, and Windows CMD

**Comment by ajmeese7** [comment]
Closing issue due to inactivity. If you are still having a problem, respond and I will reopen the issue
