### ISSUE TITLE
Can't use spambot :|

### ISSUE THREAD

**Issue by TheMossyMinerYT** [ajmeese7/spambot#25]
I get this error:

const config = require(config.json);
                       ^

ReferenceError: Cannot access 'config' before initialization
    at Object.<anonymous> (C:\Users\Devan\Desktop\Coding crap\spambot\Classic\bot.js:3:24)
[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m

**Comment by RealAwesomeness** [comment]
Is there a file called config.json in the spambot folder?

**Comment by TheMossyMinerYT** [comment]
Yes, obviously

**Comment by ajmeese7** [comment]
The file name needs to be in quotes like in the project: `'./config.json'`. Right now you're passing `config.json` as a variable that's undefined, so it doesn't know how to react. Let me know if this helps so we can resolve this issue.

**Comment by ajmeese7** [comment]
Closing this issue due to inactivity. If you still require assistance, let me know and I will reopen it to see what we can do. Cheers!
