### ISSUE TITLE
i cant open the selfbot or use it

### ISSUE THREAD

**Issue by simpu-san** [ajmeese7/spambot#26]
i get the error
Error: Cannot find module 'C:\Users\Jyedb\OneDrive\Documents\yes\.github\bot.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:898:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []

**Comment by ajmeese7** [comment]
What command did you run to get that error?

**Comment by ajmeese7** [comment]
Closing this issue due to inactivity. If you still require assistance, let me know and I will reopen it to see what we can do. Cheers!
