### ISSUE TITLE
got a Syntax error when trying to run it

### ISSUE THREAD

**Issue by GhostRadarZ** [ajmeese7/spambot#4]
Microsoft Windows [Version 10.0.16299.431]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\GhostRadarZ\Documents\New folder\spambot>node bot.js
C:\Users\GhostRadarZ\Documents\New folder\spambot\bot.js:8
client.on("message", async message => {
                           ^^^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

C:\Users\GhostRadarZ\Documents\New folder\spambot>

really not sure why was hoping you could solve it

**Comment by ajmeese7** [comment]
I'm not entirely sure. I just tried running it on my desktop using Node.js 8.11.1 (x64) and using Windows CMD and it worked for me. Did you install the node modules using `npm install`?

**Comment by ajmeese7** [comment]
Did you set a bot token and prefix?

**Comment by ajmeese7** [comment]
Closing issue due to inactivity. If you are still having a problem, respond and I will reopen the issue
