### ISSUE TITLE
Discord token not working on multiple accs

### ISSUE THREAD

**Issue by a13bfg** [ajmeese7/spambot#44]
i have 4 accs using the same code but different projects i paste my discord token but i get this 

Ready to level up!
/home/runner/spambot-4/node_modules/discord.js/src/client/ClientDataManager.js:81
        guild.channels.set(channel.id, channel);
                                   ^

TypeError: Cannot read property 'id' of undefined
    at ClientDataManager.newChannel (/home/runner/spambot-4/node_modules/discord.js/src/client/ClientDataManager.js:81:36)
    at Guild.setup (/home/runner/spambot-4/node_modules/discord.js/src/structures/Guild.js:307:68)
    at new Guild (/home/runner/spambot-4/node_modules/discord.js/src/structures/Guild.js:74:12)
    at ClientDataManager.newGuild (/home/runner/spambot-4/node_modules/discord.js/src/client/ClientDataManager.js:26:19)
    at ReadyHandler.handle (/home/runner/spambot-4/node_modules/discord.js/src/client/websocket/packets/handlers/Ready.js:20:91)
    at WebSocketPacketManager.handle (/home/runner/spambot-4/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/home/runner/spambot-4/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/home/runner/spambot-4/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/home/runner/spambot-4/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:314:20)
exit status 1

**Comment by ajmeese7** [comment]
This is the same error as #42, you need to update to the latest version of the project to get the fix :)
