### ISSUE TITLE
Spam bot has an error

### ISSUE THREAD

**Issue by Aspect-Arch** [ajmeese7/spambot#45]
so i was gonna use your spam bot, and when i do `node bot.js`
this is the error that comes out
`  spambot node bot.js
Ready to level up!
There was an error! Did you update the config.json file? If you did, let me know what the error message says in an issue on the repo on GitHub. 
 Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (/home/aspect/spambot/node_modules/discord.js/src/client/ClientManager.js:48:41)
    at Object.onceWrapper (node:events:472:26)
    at WebSocketConnection.emit (node:events:365:28)
    at WebSocketConnection.onClose (/home/aspect/spambot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:393:10)
    at WebSocket.onClose (/home/aspect/spambot/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (node:events:365:28)
    at WebSocket.emitClose (/home/aspect/spambot/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (/home/aspect/spambot/node_modules/ws/lib/websocket.js:850:15)
    at TLSSocket.emit (node:events:377:35)
    at node:net:661:12
`

Help me please!
Also, aspect is my home directory.

**Comment by ajmeese7** [comment]
Did you follow the instructions in the README to configure the project with your login token?

**Comment by Aspect-Arch** [comment]
Yes I did Ajmeese

**Comment by ajmeese7** [comment]
Can you show me the structure of your `config.json` file? Not the actual tokens, just the JSON schema around them. I want to double check to make sure there are no errors on your end that I could easily fix.

**Comment by Aspect-Arch** [comment]
`{
  "botToken": ["My Token", "if you want multiple accounts, put any other tokens here" ],
  "prefix": "/"
}
`
that is what is in my config.json file

**Comment by ajmeese7** [comment]
See #46
