### ISSUE TITLE
Error message.

### ISSUE THREAD

**Issue by ToonDiscord** [ajmeese7/spambot#46]
 node bot.js
Ready to level up!
There was an error! Did you update the config.json file? If you did, let me know what the error message says in an issue on the repo on GitHub. 
 Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (/home/runner/spambot/node_modules/discord.js/src/client/ClientManager.js:48:41)
    at Object.onceWrapper (events.js:421:26)
    at WebSocketConnection.emit (events.js:314:20)
    at WebSocketConnection.onClose (/home/runner/spambot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:393:10)
    at WebSocket.onClose (/home/runner/spambot/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.emitClose (/home/runner/spambot/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (/home/runner/spambot/node_modules/ws/lib/websocket.js:850:15)
    at TLSSocket.emit (events.js:326:22)
    at net.js:675:12

here is my code in config.js

{
  "botToken": [ "wngiher9ughEAHudhsiufhds.YJC6Mw.5SYHv348OOvOPiTqvOzh9z2JAtg", "if you want multiple accounts, put any other tokens here" ],
  "prefix": "/"
}

**Comment by ajmeese7** [comment]
You need to delete the string that says `"if you want multiple accounts, put any other tokens here"` and the comma after the first string. That is not a valid token and is why the program is crashing.
