### ISSUE TITLE
error when starting up the bot 

### ISSUE THREAD

**Issue by CS223** [ajmeese7/spambot#6]
This is the error I get when I start the bot this is the first time using this bot and I'm on a mac  
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/Users/CS/Downloads/Level up/bot.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:

**Comment by ajmeese7** [comment]
Hey CS223. I've never tested this on a Mac but I assume it should work the same. Can you explain exactly what commands you're running? I need to make sure you're following the README and doing everything properly so I can help you to the best of my abilities

**Comment by CS223** [comment]
Its all good iv fixed i just had missed up the installation but thanks
