### ISSUE TITLE
hey i keep getting invalid token 

### ISSUE THREAD

**Issue by triplethreat1469** [ajmeese7/spambot#61]
i can login in wtih the token but if i feed the bot it i gives me a invlaid token every time

**Comment by triplethreat1469** [comment]
the error is Ready to level up!
There was an error! Did you update the config.json file? If you did, let me know what the error message says in an issue on the repo on GitHub. 
 Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (/home/vm/spambot/node_modules/discord.js/src/client/ClientManager.js:48:41)
    at Object.onceWrapper (events.js:421:26)
    at WebSocketConnection.emit (events.js:314:20)
    at WebSocketConnection.onClose (/home/vm/spambot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:393:10)
    at WebSocket.onClose (/home/vm/spambot/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.emitClose (/home/vm/spambot/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (/home/vm/spambot/node_modules/ws/lib/websocket.js:850:15)
    at TLSSocket.emit (events.js:326:22)
    at net.js:676:12

**Comment by ajmeese7** [comment]
Can you walk me through the steps you took to get to that point?

**Comment by ajmeese7** [comment]
Closing due to inactivity, please reach out if you still need any assistance!
