### ISSUE TITLE
Error: Incorrect login details were provided

### ISSUE THREAD

**Issue by emeraldstone996** [ajmeese7/spambot#64]
As soon as the ready to level up! message appears, an errors pops up saying incorrect login details were provided. I cant figure out what went wrong, the token is definitely correct I've triple checked it

**Comment by emeraldstone996** [comment]
the error;
There was an error! Did you update the config.json file? If you did, let me know what the error message says in an issue on the repo on GitHub.
 Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (C:\Users\danie\spambot\node_modules\discord.js\src\client\ClientManager.js:48:41)
    at Object.onceWrapper (node:events:642:26)
    at WebSocketConnection.emit (node:events:527:28)
    at WebSocketConnection.onClose (C:\Users\danie\spambot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:393:10)
    at WebSocket.onClose (C:\Users\danie\spambot\node_modules\ws\lib\event-target.js:124:16)
    at WebSocket.emit (node:events:527:28)
    at WebSocket.emitClose (C:\Users\danie\spambot\node_modules\ws\lib\websocket.js:191:10)
    at TLSSocket.socketOnClose (C:\Users\danie\spambot\node_modules\ws\lib\websocket.js:850:15)
    at TLSSocket.emit (node:events:539:35)
    at node:net:709:12

**Comment by emeraldstone996** [comment]
Just want to make sure I've provided all the necessary details my edited code looks like this:
{
  "botToken": [ "TOKEN" ],
  "prefix": "/"
}

I got the token by logging into my discord account and pressing ctrl shift I, then selecting application, toggle device toolbar and searching for token. Then I did edit value and copied the token, then pasted it into the code where it says 'TOKEN' then I got the log in error, so I tried getting the token by going to network, ctrl shift r, searching messages and clicking that then copying the code after 'authorization' and this resulted in the same error.

**Comment by ajmeese7** [comment]
Hey @emeraldstone996 sorry to hear that, this sounds like a tricky issue. I'm incredibly busy right now but I'll try to come back and help you with this as soon as I can

**Comment by emeraldstone996** [comment]
of course get back to me whenever you can

**Comment by ajmeese7** [comment]
@emeraldstone996 do you have a `package-lock.json` file that I could take a look at?

**Comment by ajmeese7** [comment]
Closing this due to inactivity for now, please reach out if you still require assistance and I would be happy to open the issue back up! Be sure to tag me so I don't miss it :)
