### ISSUE TITLE
Update the script to discord.js-selfbot-v13

### ISSUE THREAD

**Issue by localht** [ajmeese7/spambot#69]
could you update the script to discord.js-selfbot-v13
as the following error always comes up after a few seconds of usage of the script with discord.js-selfbot (djsv12)

error :

```
/data/data/com.termux/files/home/spambot/node_modules/discord.js/src/client/actions/MessageCreate.js:31
        const message = channel._cacheMessage(new Message(channel, data, client));
                                ^

TypeError: channel._cacheMessage is not a function
    at MessageCreateAction.handle (/data/data/com.termux/files/home/spambot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:33)
    at MessageCreateHandler.handle (/data/data/com.termux/files/home/spambot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:8:51)
    at WebSocketPacketManager.handle (/data/data/com.termux/files/home/spambot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/data/data/com.termux/files/home/spambot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/data/data/com.termux/files/home/spambot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/data/data/com.termux/files/home/spambot/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (node:events:537:28)
    at Receiver.receiverOnMessage (/data/data/com.termux/files/home/spambot/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (node:events:537:28)
    at Receiver.dataMessage (/data/data/com.termux/files/home/spambot/node_modules/ws/lib/receiver.js:422:14)
```

Node.js v18.4.0

**Comment by ajmeese7** [comment]
Unless something has changed since I last worked on this, Discord.js v13 does not support selfbots at all, which is why I forked v12 and use that for this application.

**Comment by localht** [comment]
bro i said discord.js-SELFBOT-V13 not discord.js v13
you can search " npm discord.js-selfbot-v13 " and go on npmjs.com to get more information about it

**Comment by ajmeese7** [comment]
If you have any supporting information as to why you think this transition would benefit this project, I would be happy to hear it.

**Comment by ajmeese7** [comment]
Can't replicate the issue, bot works fine for me on a fresh install.
