### ISSUE TITLE
DiscordAPI Error

### ISSUE THREAD

**Issue by ridx807** [ajmeese7/spambot#71]
```log
DiscordAPIError: Unknown Message
    at /storage/emulated/0/spambot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15
    at /storage/emulated/0/spambot/node_modules/snekfetch/src/index.js:215:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      path: '/api/v7/channels/727711602413142089/messages/1063436968828092526',
      code: 10008,
      method: 'DELETE'
    }
```

How do I fix this?

**Comment by ajmeese7** [comment]
When do you encounter this error?

**Comment by ridx807** [comment]
> 

Start bot

**Comment by ridx807** [comment]
> When do you encounter this error?

But this script work, message sender perfectly, but i thinks this script failed to delete message, i dont know exactly..

**Comment by ridx807** [comment]
I want to ask, its this script can spam and delete message?

**Comment by RidhoNGPX** [comment]
same eror bro

**Comment by ajmeese7** [comment]
I just downloaded and ran a fresh copy and couldn't replicate this error, it sends and deletes messages without issue. What version of Node do you have and what OS are you on?

**Comment by ridx807** [comment]
> I just downloaded and ran a fresh copy and couldn't replicate this error, it sends and deletes messages without issue. What version of Node do you have and what OS are you on?

I run this on termux with nodejs 19.4.0

**Comment by ridx807** [comment]
> I just downloaded and ran a fresh copy and couldn't replicate this error, it sends and deletes messages without issue. What version of Node do you have and what OS are you on?

I have tried on my Windows 10, and the problem is the same.

**Comment by ridx807** [comment]
> I just downloaded and ran a fresh copy and couldn't replicate this error, it sends and deletes messages without issue. What version of Node do you have and what OS are you on?

After i try lates script, new error like this
Iam using latest nodejs and lates discord.js
```~/spambot $ node bot.js
Ready to level up!
/data/data/com.termux/files/home/spambot/node_modules/discord.js/src/client/actions/MessageDelete.js:15
      message = channel.messages.get(data.id);
                                 ^

TypeError: Cannot read properties of undefined (reading 'get')
    at MessageDeleteAction.handle (/data/data/com.termux/files/home/spambot/node_modules/discord.js/src/client/actions/MessageDelete.js:15:34)
    at MessageDeleteHandler.handle (/data/data/com.termux/files/home/spambot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageDelete.js:8:51)
    at WebSocketPacketManager.handle (/data/data/com.termux/files/home/spambot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/data/data/com.termux/files/home/spambot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/data/data/com.termux/files/home/spambot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/data/data/com.termux/files/home/spambot/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/data/data/com.termux/files/home/spambot/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/data/data/com.termux/files/home/spambot/node_modules/ws/lib/receiver.js:422:14)

Node.js v19.4.0```
