### ISSUE TITLE
Error when running bot.

### ISSUE THREAD

**Issue by ali6836** [ajmeese7/spambot#9]
Alis-MacBook-Pro:spambot Ali$ node bot.js
/Users/Ali/spambot/bot.js:8
client.on("message", async message => {
                     ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

Thats the error im getting

The ^^^^^ is under async

**Comment by ajmeese7** [comment]
Can you show me what commands you used up to that point to get the bot working? Did you do `npm install` in the spambot folder like the README says?

**Comment by ali6836** [comment]
Fixed by updating node to latest version
